version: '3.9'

services:
  reverseproxy:
    container_name: reverse-proxy
    depends_on: 
      - curity-idsvr-admin
      - curity-idsvr-runtime
    image: reverse-proxy:local
    build:
      context: .
      dockerfile: ./reverse-proxy/Dockerfile
      labels:
        - "env=local"
    ports:
      - 443:443
    restart: always

  postgresdb:
    container_name: postgres-db
    image: postgres-db:local
    build: 
      context: postgres-config
      labels:
        - "env=local"
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    restart: always

  curity-idsvr-admin: # admin node
    container_name: curity-idsvr-admin
    image: curity-idsvr:local
    command: ["sh", "-c", "idsvr -s admin"]
    build: 
      context: idsvr-config
      labels:
        - "env=local"
    environment:
      PASSWORD: password123
      LOGGING_LEVEL: DEBUG
    links:
      - postgresdb
    restart: always
  
  curity-idsvr-runtime: # runtime-node
    container_name: curity-idsvr-runtime
    depends_on: 
      - curity-idsvr-admin
    image: curity-idsvr:local
    deploy:
      replicas: 1
    build: 
      context: idsvr-config
      labels:
        - "env=local"
    environment:
      SERVICE_ROLE: default
      LOGGING_LEVEL: DEBUG
    links:
      - postgresdb
    restart: always