version: '3.9'

services:
  reverseproxy:
    container_name: reverse-proxy
    image: reverse-proxy
    build:
      context: .
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - 443:443
    restart: always

  postgresdb:
    container_name: postgres-db
    image: postgres-db
    build: 
      context: postgres-config
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    restart: always

  idsvr:
    container_name: curity-idsvr
    depends_on:
      - reverseproxy 
    image: curity-idsvr
    build: 
      context: idsvr-config
    ports:
      - 6749:6749
      - 8443:8443
    environment:
      PASSWORD: password123
      LOGGING_LEVEL: DEBUG
    links:
      - postgresdb
    restart: always
  